// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJhWdH7sfKhKKxMyHbxO2p0Rm16QGGco',
    appId: '1:721524295421:web:1249313ca075bd68802094',
    messagingSenderId: '721524295421',
    projectId: 'fir-giris-6e39f',
    authDomain: 'fir-giris-6e39f.firebaseapp.com',
    storageBucket: 'fir-giris-6e39f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQs5aHYtiNO66mzrCRcfnIMeohtZoGTn0',
    appId: '1:721524295421:android:92d296c692a2462a802094',
    messagingSenderId: '721524295421',
    projectId: 'fir-giris-6e39f',
    storageBucket: 'fir-giris-6e39f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbc0n3qy34IokHWqlmvImr5VbPq9o72H4',
    appId: '1:721524295421:ios:666c35d7c8d5c579802094',
    messagingSenderId: '721524295421',
    projectId: 'fir-giris-6e39f',
    storageBucket: 'fir-giris-6e39f.appspot.com',
    iosBundleId: 'com.example.firebaseGiris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbc0n3qy34IokHWqlmvImr5VbPq9o72H4',
    appId: '1:721524295421:ios:52338b4ed60c16d8802094',
    messagingSenderId: '721524295421',
    projectId: 'fir-giris-6e39f',
    storageBucket: 'fir-giris-6e39f.appspot.com',
    iosBundleId: 'com.example.firebaseGiris.RunnerTests',
  );
}
